@startuml
actor User
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":DeleteCommand" as DeleteCommand
participant ":TransactionList" as TransactionList

User -> Ui : delete 2
activate Ui

Ui -> Parser : parse("delete 2")
activate Parser
Parser --> Ui : DeleteCommand
deactivate Parser

Ui -> DeleteCommand : execute(list, budget, ui)
activate DeleteCommand

DeleteCommand -> TransactionList : delete(index)
activate TransactionList
TransactionList --> DeleteCommand : success
deactivate TransactionList

DeleteCommand -> Ui : showMessage()
deactivate DeleteCommand

deactivate Ui
@enduml