@startuml
actor User
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":ListCommand" as ListCommand
participant ":TransactionList" as TransactionList

User -> Ui : list
activate Ui

Ui -> Parser : parse("list")
activate Parser
Parser --> Ui : ListCommand
deactivate Parser

Ui -> ListCommand : execute(list, budget, ui)
activate ListCommand

ListCommand -> TransactionList : getAllTransactions()
activate TransactionList
TransactionList --> ListCommand : transactions
deactivate TransactionList

ListCommand -> Ui : show(transactions)
deactivate ListCommand

Ui --> User : display transactions
deactivate Ui
@enduml